### ISSUE TITLE
Project's setup

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#1]
Create project, its initial setup and its modules.

- [x] Create project on Xcode #2
- [x] Setup Swiftlint #4
- [x] Add Swiftgen #6
- [x] Create Domain module #3
- [x]  Create Data's modules #9
- [x] Create Presentation's Common module #11 
- [x] Create Navigation module #12
- [x] Create Dependency Injection module #13
