### ISSUE TITLE
Search Twitter's users by username

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#18]
- [x] Create user module #19
- [x] Create integration layer for Users #20
- [x] Create presentation's layer for Users #21
- [x] Add OAuth authentication #30
