### ISSUE TITLE
Create integration layer for Users

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#20]
- [x] Create Domain's layer for Users
- [x] Add tests for Domain's layer
- [x] Create Data's layer for Users
- [x] Add tests for Data's layer
- [x] Create Networking's layer for Users
https://api.twitter.com/1.1/users/lookup.json?screen_name=AdrianoDiasX93
- [x] Add tests for Networking's layer
