### ISSUE TITLE
Create presentation's layer for Users

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#21]
- [x] Create template files (Models, ViewModels, Views, Coordinators...)
- [x] Add injections
- [x] Add tests for ViewModels & Coordinators
- [x] Add and bind UI
![IMG_2EDB020B72B8-1](https://user-images.githubusercontent.com/5974969/94376483-243c9300-00f1-11eb-9f44-f852fbfd225c.jpeg)
- [x] Manual tests
