### ISSUE TITLE
Show public tweets from selected user

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#22]
- [x] Create tweets module #23
- [x] Create integration layer for Tweets #24
- [x] Create presentation's layer for Tweets #25
