### ISSUE TITLE
Create integration layer for Tweets

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#24]
- [x] Create Domain's layer for Tweets
- [x] Add tests for Domain's layer
- [x] Create Data's layer for Tweets
- [x] Add tests for Data's layer
- [x] Create Networking's layer for Tweets
https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=AdrianoDias93
- [x] Add tests for Networking's layer
