### ISSUE TITLE
Create presentation's layer for Tweets

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#25]
- [x] Create template files (Models, ViewModels, Views, Coordinators...)
- [x] Add tests for ViewModels & Coordinators
- [x] Add injections
- [x] Add and bind UI
![IMG_A3C3809ED8F4-1](https://user-images.githubusercontent.com/5974969/94376844-8c8c7400-00f3-11eb-93ad-0d66f26e7839.jpeg)
- [x] Manual tests
