### ISSUE TITLE
Create integration layer for Sentiment

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#38]
- [x] Create Domain's layer for Sentiments
- [x] Add tests for Domain's layer
- [x] Create Data's layer for Sentiments
- [x] Add tests for Data's layer
- [x] Create Networking's layer for Sentiments
- [x] Add tests for Networking's layer
