### ISSUE TITLE
Create presentation's layer for Sentiments

### ISSUE THREAD

**Issue by adrianod1as** [adrianodiasx93/TheFeels#39]
- [x] Create template files
- [x] Add tests for ViewModels & Coordinators
- [x] Add injections
- [x] Add and bind UI
- [x] Manual tests
